# Generated by Django 3.0.8 on 2020-07-20 01:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beneficiario',
            name='CPF',
        ),
        migrations.AddField(
            model_name='beneficiario',
            name='nome',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='nome_beneficiario', to='Usuarios.Usuario'),
            preserve_default=False,
        ),
    ]
