# Generated by Django 3.0.8 on 2020-07-21 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0002_auto_20200719_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiario',
            name='renda',
            field=models.CharField(blank=True, max_length=7),
        ),
        migrations.AlterField(
            model_name='beneficiario',
            name='data_beneficio',
            field=models.DateField(blank=True, null=True),
        ),
    ]
