# Generated by Django 3.2.6 on 2021-08-29 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Beneficiarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='localidade',
            name='bairro',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Beneficiarios.bairro'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='localidade',
            name='localidade',
            field=models.CharField(max_length=100),
        ),
    ]
