# Generated by Django 3.2.6 on 2021-08-29 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Beneficiarios', '0002_auto_20210829_1403'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100)),
            ],
        ),
    ]
